In [5]:
import numpy as np
import h5py
import pandas as pd
from pandas import DataFrame, Series
import torch
import e3nn
torch.set_default_dtype(torch.float64)

In [3]:
# read equilibrium geometry data
with h5py.File("carbon_monoxide-b3lyp_d3bj-631gd-gas-equilibrium_geometry.hdf5", "r") as h5:
    equilibrium_geometry = np.array(h5.get("equilibrium_geometry"))
    atomic_numbers = np.array(h5.get("atomic_numbers"))
    isotropic_shieldings = np.array(h5.get("isotropic_shieldings"))
    hirshfeld_charges = np.array(h5.get("hirshfeld_charges"))
    mulliken_charges = np.array(h5.get("mulliken_charges"))

In [7]:
# print out equilibrium data
print("equilibrium geometry")
print(equilibrium_geometry)
equilibrium_list = [atomic_numbers, isotropic_shieldings, hirshfeld_charges, mulliken_charges]
equilibrium_list = np.array(equilibrium_list).T.copy()
columns = ["Z", "sigma", "z_hir", "z_mul"]
equilibrium_df = DataFrame(equilibrium_list, columns=columns)
equilibrium_df.index = [ i+1 for i in range(len(equilibrium_df)) ]
equilibrium_df.index.name = "atom#"
print()
print("equilibrium properties")
display(equilibrium_df)

equilibrium geometry
[[ 0.        0.       -0.650261]
 [ 0.        0.        0.487695]]

equilibrium properties


Z    sigma   z_hir     z_mul
atom#                                
1      6.0  -3.6465  0.0828  0.143074
2      8.0 -64.8200 -0.0828 -0.143074

In [8]:
# read perturbed data
with h5py.File("carbon_monoxide-b3lyp_d3bj-631gd-gas-NMR-pcSseg_1.hdf5", "r") as h5:
    geoms_and_shieldings = np.array(h5.get("data"))

In [9]:
# print out non-equilbrium data
print("near-equilibrium data")
shape = np.shape(geoms_and_shieldings)
print(f"there are {shape[0]} geometries ({shape[1]} atoms per geometry)")
print()
geometries = geoms_and_shieldings[:,:,:3]
shieldings = geoms_and_shieldings[:,:,-1]
geoms_and_shieldings = None
print("first geometry")
print(geometries[0])
print()
print("first set of shieldings")
print(shieldings[0])

near-equilibrium data
there are 126 geometries (2 atoms per geometry)

first geometry
[[ 0.        0.       -0.428571]
 [ 0.        0.        0.321429]]

first set of shieldings
[119.2698 152.1464]
